### ISSUE TITLE
Make possible to set custom shortcut

### ISSUE THREAD

**Issue by Arcoz0308** [TZGyn/shortener#1]

**Comment by Arcoz0308** [comment]
(With possibilty of only one user)

**Comment by TZGyn** [comment]
Do you mean custom shortener code like https://shortener.com/{custom_code_here} ?
I added them in 32bf560f43487bbcb7c3e8b696b62ae0f53b9b2f

**Comment by Arcoz0308** [comment]
Hello, yes ! 
Verry nice update, thx.
